"""knowledge_assets"""
from alembic import op
import sqlalchemy as sa
revision = '03ae2f1407ba'
down_revision = 'dc5e2c78f66e'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['domains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_uuid'), ['uuid'], unique=True)

    op.create_table('knowledge_relations',
    sa.Column('from_uuid', sa.String(length=36), nullable=False),
    sa.Column('to_uuid', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('judgment', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['from_uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_relations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_from_uuid'), ['from_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_to_uuid'), ['to_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_uuid'), ['uuid'], unique=True)

    op.create_table('reuse_logs',
    sa.Column('item_uuid', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.String(length=40), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['item_uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reuse_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reuse_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reuse_logs_item_uuid'), ['item_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_reuse_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reuse_logs_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reuse_logs_uuid'), ['uuid'], unique=True)

    op.create_table('revisions',
    sa.Column('item_uuid', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('old_version', sa.JSON(), nullable=False),
    sa.Column('new_version', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['item_uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revisions_item_uuid'), ['item_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_revisions_uuid'), ['uuid'], unique=True)

    op.create_table('topics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_uuid'), ['uuid'], unique=True)

    op.create_table('cases',
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('execution', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('lessons', sa.Text(), nullable=False),
    sa.Column('mistakes', sa.Text(), nullable=False),
    sa.Column('success_factors', sa.Text(), nullable=False),
    sa.Column('failure_factors', sa.Text(), nullable=False),
    sa.Column('reusable_method', sa.Text(), nullable=False),
    sa.Column('applicable_conditions', sa.Text(), nullable=False),
    sa.Column('not_applicable_conditions', sa.Text(), nullable=False),
    sa.Column('future_improvements', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_case_type'), ['case_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_is_reviewed'), ['is_reviewed'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_uuid'), ['uuid'], unique=True)

    op.create_table('knowledge',
    sa.Column('knowledge_type', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('learned_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('maturity_level', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.String(length=40), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.CheckConstraint('maturity_level >= 1 AND maturity_level <= 6'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_knowledge_type'), ['knowledge_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_maturity_level'), ['maturity_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_next_review_date'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_uuid'), ['uuid'], unique=True)

    op.create_table('learning_records',
    sa.Column('learning_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('application', sa.Text(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('maturity_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_records_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_learning_type'), ['learning_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_maturity_level'), ['maturity_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_uuid'), ['uuid'], unique=True)

    op.create_table('problems',
    sa.Column('occurred_date', sa.Date(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('possible_causes', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('final_solution', sa.Text(), nullable=False),
    sa.Column('execution', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('recurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_recurred_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_occurred_date'), ['occurred_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_uuid'), ['uuid'], unique=True)

    op.create_table('solutions',
    sa.Column('problem_type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('advantages', sa.Text(), nullable=False),
    sa.Column('disadvantages', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('cost', sa.String(length=300), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('success_rate_note', sa.Text(), nullable=False),
    sa.Column('applicable_conditions', sa.Text(), nullable=False),
    sa.Column('not_applicable_conditions', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solutions_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_solutions_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solutions_problem_type'), ['problem_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_solutions_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_solutions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solutions_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_solutions_verification_status'), ['verification_status'], unique=False)

    op.create_table('sources',
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('access_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_uuid'), ['uuid'], unique=True)

    op.create_table('case_events',
    sa.Column('case_uuid', sa.String(length=36), nullable=False),
    sa.Column('event_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_uuid'], ['cases.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_uuid'], ['events.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_uuid', 'event_uuid')
    )
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.create_index('ix_case_events_reverse', ['event_uuid', 'case_uuid'], unique=False)

    op.create_table('case_tasks',
    sa.Column('case_uuid', sa.String(length=36), nullable=False),
    sa.Column('task_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_uuid'], ['cases.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_uuid'], ['tasks.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_uuid', 'task_uuid')
    )
    with op.batch_alter_table('case_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_case_tasks_reverse', ['task_uuid', 'case_uuid'], unique=False)

    op.create_table('experiences',
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('source_case_uuid', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('times_verified', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=40), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_case_uuid'], ['cases.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uuid'], ['entries.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_source_case_uuid'), ['source_case_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_times_used'), ['times_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=False, server_default='entries'))
        batch_op.add_column(sa.Column('origin', sa.String(length=30), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('content_nature', sa.String(length=30), nullable=False, server_default='unknown'))
        batch_op.add_column(sa.Column('original_content', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('normalized_content', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('generated_by_ai', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('generated_at', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_entries_content_nature'), ['content_nature'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_origin'), ['origin'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_type', sa.String(length=50), nullable=False, server_default='day'))
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('target_uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('what_went_well', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('what_went_wrong', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('lessons', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('next_action', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('expectations', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('chance_factors', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('reconsideration', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('keep_methods', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('avoid_methods', sa.Text(), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_reviews_target_uuid'), ['target_uuid'], unique=False)
        batch_op.create_foreign_key('fk_reviews_target_uuid', 'entries', ['target_uuid'], ['uuid'], ondelete='SET NULL')

    op.execute("UPDATE entries SET original_content = content")
    if op.get_bind().dialect.name == 'sqlite':
        for name in ('entries_ai', 'entries_ad', 'entries_au'):
            op.execute('DROP TRIGGER IF EXISTS ' + name)
        op.execute('DROP TABLE IF EXISTS entries_fts')
        op.execute("CREATE VIRTUAL TABLE entries_fts USING fts5(title,content,summary,normalized_content,content='entries',content_rowid='id',tokenize='trigram')")
        op.execute("CREATE TRIGGER entries_ai AFTER INSERT ON entries BEGIN INSERT INTO entries_fts(rowid,title,content,summary,normalized_content) VALUES(new.id,new.title,new.content,new.summary,new.normalized_content); END")
        op.execute("CREATE TRIGGER entries_ad AFTER DELETE ON entries BEGIN INSERT INTO entries_fts(entries_fts,rowid,title,content,summary,normalized_content) VALUES('delete',old.id,old.title,old.content,old.summary,old.normalized_content); END")
        op.execute("CREATE TRIGGER entries_au AFTER UPDATE ON entries BEGIN INSERT INTO entries_fts(entries_fts,rowid,title,content,summary,normalized_content) VALUES('delete',old.id,old.title,old.content,old.summary,old.normalized_content); INSERT INTO entries_fts(rowid,title,content,summary,normalized_content) VALUES(new.id,new.title,new.content,new.summary,new.normalized_content); END")
        op.execute("INSERT INTO entries_fts(entries_fts) VALUES('rebuild')")

def downgrade():
    raise RuntimeError('For data safety, schema downgrade is disabled. Restore a backup with the matching app version.')
